CREATE TABLE PRODUCTS(
	PRODUCTNUM NUMBER,
	PRODUCTNAME VARCHAR2(200) NOT NULL,
	PRODUCTRATE NUMBER(4, 2),
	PRODUCTDATE DATE,
	PRODUCTDETAIL CLOB,
	CONSTRAINT PRODUCTNUM_PK PRIMARY KEY(PRODUCTNUM)
	
);



CREATE TABLE USERS (
	USERNAME VARCHAR2(200) PRIMARY KEY,
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	PHONE VARCHAR2(200),
	EMAIL VARCHAR2(200),
	CONSTRAINT PHONE_U UNIQUE(PHONE),
	CONSTRAINT EMAIL_U UNIQUE(EMAIL)
);


CREATE TABLE ACCOUNTS(
	ACCOUNTNUM VARCHAR2(200) PRIMARY KEY,
	USERNAME VARCHAR2(200),
	PRODUCTNUM NUMBER,
	ACCOUNTBALANCE NUMBER DEFAULT 0 NOT NULL,
	ACCOUNTDATE DATE NOT NULL,
	CONSTRAINT U_NAME_FK FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),
	CONSTRAINT PDT_NUM_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCTS(PRODUCTNUM)
);

DROP TABLE TRADE;
DROP TABLE ACCOUNTS;
SELECT * FROM ACCOUNTS;
ALTER TABLE ACCOUNTS DROP COLUMN ACCOUNTBALANCE;
ALTER TABLE ACCOUNTS ADD (ACCOUNTBALANCE NUMBER NOT NULL);
ALTER TABLE ACCOUNTS ADD CONSTRAINT ACCB_NN NOT NULL(ACCOUNTBALANCE);

COMMIT;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ACCOUNTS';

CREATE TABLE TRADE(
	TRADENUM NUMBER PRIMARY KEY,
	ACCOUNTNUM VARCHAR2(200),
	TRADEAMOUNT NUMBER,
	TRADEKIND NUMBER(1),
	TRADEBALANCE NUMBER,
	TRADEDATE DATE NOT NULL,
	CONSTRAINT ACC_N_FK FOREIGN KEY(ACCOUNTNUM) REFERENCES ACCOUNTS(ACCOUNTNUM)
);

SELECT * FROM TRADE;


CREATE TABLE CARTS(
	USERNAME VARCHAR2(200),
	PRODUCTNUM NUMBER,
	CONSTRAINT U_C_FK FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),
	CONSTRAINT PDT_C_FK FOREIGN KEY(PRODUCTNUM) REFERENCES PRODUCTS(PRODUCTNUM)
)


SELECT * FROM TAB;


----------------------------------------------------------------------------------------------


SELECT * FROM USERS;
INSERT INTO USERS
VALUES ('1', '1234', 'asd', '010-1234-5678', 'abc@def.gh');

INSERT INTO USERS (USERNAME, PASSWORD, NAME, PHONE, EMAIL)
VALUES (?, ?, ?, ?, ?)

CREATE SEQUENCE TRD_NUM_SEQ;
CREATE SEQUENCE PDT_NUM_SEQ;

SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS (PRODUCTNUM, PRODUCTNAME, PRODUCTDATE)
VALUES (PDT_NUM_SEQ.NEXTVAL, 'qwe', SYSDATE);


SELECT * FROM ACCOUNTS;
INSERT INTO ACCOUNTS (ACCOUNTNUM, USERNAME, PRODUCTNUM, ACCOUNTDATE)
VALUES ('94642', '1', 1, SYSDATE);
INSERT INTO ACCOUNTS (ACCOUNTNUM, USERNAME, PRODUCTNUM, ACCOUNTDATE, ACCOUNTBALANCE)
 VALUES ('45667', '1', 1, SYSDATE, 1000);


SELECT * FROM TRADE;
INSERT INTO TRADE (TRADENUM, ACCOUNTNUM, TRADEAMOUNT, TRADEKIND, TRADEBALANCE, TRADEDATE)
VALUES (TRD_NUM_SEQ.NEXTVAL, '94642', NULL, NULL, NULL, SYSDATE);


SELECT * FROM CARTS;
INSERT INTO CARTS (USERNAME, PRODUCTNUM)
VALUES ('1', 1);


SELECT USERNAME, NAME, PHONE, EMAIL
FROM USERS WHERE USERNAME = ?;


SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS (PRODUCTNUM, PRODUCTNAME, PRODUCTRATE, PRODUCTDATE, PRODUCTDETAIL)
VALUES (PDT_NUM_SEQ.NEXTVAL, ?, ?, ?, ?)

SELECT * FROM PRODUCTS
WHERE PRODUCTNUM = ?;

UPDATE PRODUCTS SET PRODUCTRATE = ?
WHERE PRODUCTNUM = ?;

