SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
-- Basic --
-- 1.
SELECT DEPARTMENT_NAME|| "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3.
SELECT STUDENT_NAME
FROM TB_STUDENT s
JOIN TB_DEPARTMENT td
ON S.DEPARTMENT_NO = TD.DEPARTMENT_NO
WHERE TD.DEPARTMENT_NAME = '국어국문학과'
AND S.ABSENCE_YN LIKE 'Y'
AND S.STUDENT_SSN LIKE '_______2______';

-- 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '_2_____'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';


-- Function --
-- 1.
SELECT STUDENT_NO "학번", STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO LIKE '002'
ORDER BY ENTRANCE_DATE ASC

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3 ;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 5) AS 이름
FROM TB_PROFESSOR

-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE - TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')



--- DML ---
-- 1.
DROP TABLE TB_CLASS_TYPE;
CREATE TABLE TB_CLASS_TYPE (
	번호 VARCHAR(2),
	유형이름 VARCHAR2(20)
)

SELECT * FROM TAB;
SELECT * FROM TB_CLASS_TYPE;

INSERT INTO TB_CLASS_TYPE
VALUES ('01', '전공필수');
INSERT INTO TB_CLASS_TYPE
VALUES ('02', '전공선택');
INSERT INTO TB_CLASS_TYPE
VALUES ('03', '교양필수');
INSERT INTO TB_CLASS_TYPE
VALUES ('04', '교양선택');
INSERT INTO TB_CLASS_TYPE
VALUES ('05', '논문지도');


-- 2.
SELECT * FROM TB_STUDENT;

DROP TABLE TB_학생일반정보;
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
FROM TB_STUDENT;

SELECT * FROM TB_학생일반정보;


-- 3.

SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR;

DROP TABLE TB_국어국문학과;

CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RRRR'), 'YYYY') 출생년도, PROFESSOR_NAME 교수이름 
FROM TB_STUDENT S
JOIN TB_PROFESSOR P
ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
JOIN TB_DEPARTMENT D
ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE D.DEPARTMENT_NAME = '국어국문학과';

SELECT * FROM TB_국어국문학과;


-- 4.
UPDATE TB_DEPARTMENT SET CAPACITY = ROUND(CAPACITY * 1.1, 0);

SELECT * FROM TB_DEPARTMENT;



-- 5.
UPDATE TB_STUDENT SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

SELECT * FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';


-- 6.
UPDATE TB_STUDENT SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);
SELECT * FROM TB_STUDENT;


-- 7.
SELECT * FROM TB_GRADE;
SELECT * FROM TB_CLASS
WHERE CLASS_NAME = '피부생리학';

UPDATE TB_GRADE G SET POINT = 3.5
WHERE TERM_NO = '200501'
AND STUDENT_NO = (SELECT STUDENT_NO
				FROM TB_STUDENT
				WHERE STUDENT_NAME = '김명훈'
				AND DEPARTMENT_NO = (
					SELECT DEPARTMENT_NO
					FROM TB_CLASS
					WHERE CLASS_NAME = '피부생리학'
					)
				)

SELECT * FROM TB_GRADE
WHERE TERM_NO = '200501'
AND STUDENT_NO = (SELECT STUDENT_NO
				FROM TB_STUDENT
				WHERE STUDENT_NAME = '김명훈'
				AND DEPARTMENT_NO = (
					SELECT DEPARTMENT_NO
					FROM TB_CLASS
					WHERE CLASS_NAME = '피부생리학'
					)
				);


-- 8.
SELECT * FROM TB_GRADE;
SELECT * FROM TB_STUDENT;
SELECT STUDENT_NO
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

DELETE TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
					FROM TB_STUDENT
					WHERE ABSENCE_YN = 'Y'
					);


