SELECT  * FROM TAB;
SELECT * FROM SEQ;
SELECT * FROM USER_CONSTRAINTS;

-- 1.
SELECT * FROM PLAYER;

SELECT PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K05');


-- 2.
SELECT PLAYER_NAME, NATION
FROM PLAYER
WHERE NATION IS NOT NULL;


-- 3.
SELECT PLAYER_NAME, POSITION, BACK_NO, TEAM_ID, HEIGHT
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07');


-- 4.
SELECT * FROM TEAM;

SELECT TEAM_ID, ZIP_CODE1||'-'||ZIP_CODE2
FROM TEAM;


-- 5.
SELECT * FROM PLAYER;

SELECT COUNT(PLAYER_ID), COUNT(HEIGHT), MAX(HEIGHT), MIN(HEIGHT), AVG(HEIGHT)
FROM PLAYER;


-- 6.
SELECT TEAM_ID, COUNT(PLAYER_ID)
FROM PLAYER
GROUP BY TEAM_ID
ORDER BY COUNT(PLAYER_ID) DESC;


-- 7.
SELECT PLAYER_NAME, TEAM_NAME
FROM PLAYER P
NATURAL JOIN TEAM T;


-- 8.
SELECT * FROM PLAYER;
SELECT * FROM TEAM;
SELECT * FROM STADIUM;

SELECT PLAYER_NAME, POSITION, REGION_NAME, TEAM_NAME, STADIUM_NAME
FROM PLAYER P
JOIN TEAM T ON P.TEAM_ID = T.TEAM_ID
JOIN STADIUM S ON T.STADIUM_ID = S.STADIUM_ID;


-- 9.
SELECT * FROM TEAM;
SELECT * FROM STADIUM;

SELECT TEAM_NAME, TEAM_ID, STADIUM_NAME
FROM TEAM T
JOIN STADIUM S
ON T.STADIUM_ID = S.STADIUM_ID
ORDER BY STADIUM_NAME ASC;


-- 10.
SELECT * FROM PLAYER;

SELECT PLAYER_NAME, POSITION, BACK_NO
FROM PLAYER
WHERE HEIGHT > (SELECT AVG(HEIGHT) FROM PLAYER)
ORDER BY PLAYER_NAME ASC;


-- 11.
SELECT TEAM_NAME, E_TEAM_NAME, REGION_NAME
FROM TEAM
NATURAL JOIN PLAYER
WHERE PLAYER_NAME IN ('정현수');


-- 12.
CREATE OR REPLACE VIEW V_TEAM_PLAYER
AS
SELECT PLAYER_NAME, POSITION, BACK_NO, TEAM_ID, TEAM_NAME
FROM PLAYER NATURAL JOIN TEAM;

SELECT * FROM V_TEAM_PLAYER
WHERE PLAYER_NAME LIKE '황%';


-- 13.
SELECT * FROM TEAM;
CREATE SEQUENCE TEAM_ID_SEQ;
SELECT TEAM_ID_SEQ.CURRVAL FROM TEAM;
DROP SEQUENCE TEAM_ID_SEQ;

SELECT * FROM PLAYER
ORDER BY PLAYER_ID DESC;

SELECT MAX(PLAYER_ID)
FROM PLAYER;

CREATE SEQUENCE PLAYER_ID_SEQ
START WITH 2012137;

SELECT PLAYER_ID_SEQ.CURRVAL FROM DUAL;
SELECT * FROM SEQ;

INSERT INTO PLAYER (PLAYER_ID, PLAYER_NAME, TEAM_ID, JOIN_YYYY, POSITION, BIRTH_DATE, HEIGHT, WEIGHT)
VALUES (PLAYER_ID_SEQ.NEXTVAL, '박주호', 'K01', TO_CHAR(SYSDATE, YYYY), 'DF', '1987-3-16', 176, 75);


-- 14.
SELECT * FROM SCHEDULE;

SELECT SCHE_DATE, STADIUM_NAME, HT.TEAM_NAME 홈, AT.TEAM_NAME 어웨이, HOME_SCORE, AWAY_SCORE
FROM SCHEDULE SC
JOIN STADIUM S ON SC.STADIUM_ID = S.STADIUM_ID
JOIN TEAM HT ON HT.TEAM_ID = SC.HOMETEAM_ID
JOIN TEAM AT ON AT.TEAM_ID = SC.AWAYTEAM_ID
WHERE (HOME_SCORE+AWAY_SCORE) = (SELECT MAX(HOME_SCORE+AWAY_SCORE) FROM SCHEDULE)

