-- 유저 생성
-- 아무런 권한이 없다
CREATE USER user01 IDENTIFIED BY user01;

-- 권한 부여
GRANT CONNECT, RESOURCE TO user01;

-- home 유저 생성
CREATE USER home IDENTIFIED BY home;
GRANT CONNECT, RESOURCE TO home;

-- CNS 유저 생성
CREATE USER CNS IDENTIFIED BY CNS;
GRANT CONNECT, RESOURCE TO CNS;

-- FOOTBALL 유저 생성
CREATE USER FOOTBALL IDENTIFIED BY FOOTBALL;
GRANT CONNECT, RESOURCE TO FOOTBALL;
GRANT CREATE VIEW TO FOOTBALL;

-- BOOK 유저 생성
CREATE USER BOOK IDENTIFIED BY BOOK;
GRANT CONNECT, RESOURCE TO BOOK;

CREATE USER bank IDENTIFIED BY bank;
GRANT CONNECT, RESOURCE TO bank;

-- 샘플 유저 hr 사용해제 비번을 hr
ALTER USER hr ACCOUNT UNLOCK 
IDENTIFIED BY hr;

COMMIT;