SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
-- Basic --
-- 1.
SELECT DEPARTMENT_NAME|| "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3.
SELECT STUDENT_NAME
FROM TB_STUDENT s
JOIN TB_DEPARTMENT td
ON S.DEPARTMENT_NO = TD.DEPARTMENT_NO
WHERE TD.DEPARTMENT_NAME = '국어국문학과'
AND S.ABSENCE_YN LIKE 'Y'
AND S.STUDENT_SSN LIKE '_______2______';

-- 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '_2_____'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';


-- Function --
-- 1.
SELECT STUDENT_NO "학번", STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO LIKE '002'
ORDER BY ENTRANCE_DATE ASC

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3 ;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2, 5) AS 이름
FROM TB_PROFESSOR

-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE - TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR')
