-- FIRST_NAME TJ
-- 1. 부서의 관리자 의 모든 정보
-- 2. 부서의 관리자 보다 더 늦게 입사한 사람들의 평균 급여

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID =
(SELECT MANAGER_ID FROM EMPLOYEES WHERE FIRST_NAME = 'TJ'); -- 1

SELECT AVG(SALARY) FROM EMPLOYEES WHERE HIRE_DATE >
(SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID =
(SELECT MANAGER_ID FROM EMPLOYEES WHERE FIRST_NAME = 'TJ')); -- 2


-- 사원들의 정보 - 평균 급여보다 많이 받는 사람들

SELECT * FROM EMPLOYEES WHERE SALARY >
(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES WHERE SALARY =
(SELECT MAX(SALARY) FROM EMPLOYEES) OR SALARY =
(SELECT MIN(SALARY) FROM EMPLOYEES);

SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME = 'David');


-- 1. 사번이 198인 사원이 근무하는 부서가 있는 도시가 속해 있는 나라가 있는 대륙 정보
SELECT * FROM REGIONS WHERE REGION_ID =
(SELECT REGION_ID FROM COUNTRIES WHERE COUNTRY_ID =
(SELECT COUNTRY_ID FROM LOCATIONS WHERE LOCATION_ID =
(SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 198
))));


-- 2. LAST_NAME이 Khoo 인 사람의 근무하는 부서명
SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'Khoo');


-- 3. 사원번호가 199번인 사원의 매니저가 근무하는 부서가 있는 나라명 출력
SELECT COUNTRY_NAME FROM COUNTRIES WHERE COUNTRY_ID =
(SELECT COUNTRY_ID FROM LOCATIONS WHERE LOCATION_ID = 
(SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE MANAGER_ID =
(SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 199)
)));


-- 4. 사원들 중에서 월급이 가장 적은 사원이 근무하는 도시명
SELECT CITY FROM LOCATIONS WHERE LOCATION_ID = 
(SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY = 
(SELECT MIN(SALARY) FROM EMPLOYEES)
));


-- 5. 부서명이 IT인 부서에 근무하는 사원들의 모든 정보 출력
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT');


-- 6. Employees 테이블에서 LAST_NAME이 Greenberg 사원보다 급여를 더 많이 받고 있는 사원들정보 출력
SELECT * FROM EMPLOYEES WHERE SALARY >
(SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = 'Greenberg');


-- 7. 부서별 최소급여를 받고 있는 사원의 정보 출력
SELECT * FROM EMPLOYEES WHERE (DEPARTMENT_ID, SALARY) IN
(SELECT DEPARTMENT_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);


-- 8. 도시이름이 'S'로시작하는 지역에 근무하는 사원의 정보 출력
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID IN
(SELECT LOCATION_ID FROM LOCATIONS WHERE CITY LIKE 'S%' ));


-- 9. 성(LAST_NAME)이 Austin 사원의 매니저(상사)가 근무하는 부서의 평균 급여보다 부서평균이 더 큰 부서의 이름

SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID IN
(SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) >
(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID =
(SELECT MANAGER_ID FROM EMPLOYEES WHERE LAST_NAME = 'Austin'))));